### ISSUE TITLE
Unable to use Ice correctly on Windows

### ISSUE THREAD

**Issue by fabienwang** [younishd/ice#1]
Compiling to exe using py2exe
The program seems unable to launch git commands, while git is in my PATH.

![unoworkonwindows_xd](https://cloud.githubusercontent.com/assets/8741873/7610810/25c0da7a-f980-11e4-8afb-7bd4f3ee4e22.JPG)

**Comment by younishd** [comment]
@fabienwang Windows is not officially supported at the moment.

**Comment by younishd** [comment]
Closed for now.
