### ISSUE TITLE
ice needs a logo

### ISSUE THREAD

**Issue by Schoewilliam** [younishd/ice#2]
Right now, ice doesn't have any logo to display (such as in `ice help`)

**Comment by younishd** [comment]
![](http://i.memeful.com/media/post/edvJggd_700wa_0.gif)

**Comment by younishd** [comment]
@Schoewilliam So, where is it?

**Comment by younishd** [comment]
Done in https://github.com/younishd/ice/commit/43743c83955d3db3d732286e739d72c1753671f6.
